### ISSUE TITLE
About the missing file AlignNets in the  subNets folder

### ISSUE THREAD

**Issue by Zhang-Ding** [AZYoung233/CLGSI#1]
I really appreciate your work, but the file named AlignNets is missing in the subNets folder.

**Comment by AZYoung233** [comment]
Thanks for your attention, actually this repository uses unaligned data. Prior to feature fusion, feature-level alignment relied heavily on contrast learning. Since the implementation of this repository is mainly based on the work from Tsinghua University, AlignNET is actually not needed in this work. I hope this clears your doubts.
